spring:
  profiles: local
  datasource:
      driverClassName: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/postgres?currentSchema=planes
      username: plane
      password: plane
  security:
    basic:
      enabled: false
  management:
    security:
      enabled: false
  thymeleaf:
    cache: false